# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 17:15
from __future__ import unicode_literals

import cix.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ncaacards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('execution_id', cix.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(editable=False)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncaacards.NcaaGame')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', cix.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('placer', models.CharField(max_length=30)),
                ('placed_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_buy', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('cancel_on_game', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncaacards.UserEntry')),
            ],
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='trading.Market')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncaacards.GameTeam')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.Security'),
        ),
        migrations.AddField(
            model_name='execution',
            name='buy_order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='buy_executions', to='trading.Order'),
        ),
        migrations.AddField(
            model_name='execution',
            name='security',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='trading.Security'),
        ),
        migrations.AddField(
            model_name='execution',
            name='sell_order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sell_executions', to='trading.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='security',
            unique_together=set([('market', 'name')]),
        ),
    ]
