# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def populate_apids(apps, schema_editor):
    UserEntry = apps.get_model('ncaacards', 'UserEntry')
    db_alias = schema_editor.connection.alias
    for entry in UserEntry.objects.using(db_alias).all():
        entry.apid = uuid.uuid4()
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='apid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(populate_apids)
    ]
