# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0003_auto_20170318_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='estimated_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userentry',
            name='estimated_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
