# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0004_auto_20170415_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='net_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
