# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0005_userteam_net_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='entry_name',
            field=models.CharField(max_length=50),
        ),
    ]
