# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ncaacards.models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0006_auto_20170416_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw', models.CharField(default=ncaacards.models.generate_otp, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('entry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncaacards.UserEntry')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='ncaacards.NcaaGame')),
            ],
        ),
    ]
