# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0007_gameotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteam',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scoretype',
            name='default_score',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scoringsetting',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
